### ISSUE TITLE
Long compilation times in webpack's`sass-loader`

### ISSUE THREAD

**Issue by payneio** [justkey007/fomantic-ui-sass#5]
Compilation of this SCSS sheet was taking over one minute. Once I removed repetitive `@import` statements, the compile time is now down to ~8s on initial load and ~2s hot-load (which I LOVE!).

Specifically, I just removed all `@import "../globals/variables";` statements in the default theme files because `_variables.scss` is already bringing them in.

**Comment by payneio** [comment]
Oh... I also removed all the description file imports of default theme, e.g. `@import '../../themes/default/elements/header.variables';` in `definitions/elements/header.scss` since they are also brought in with `_variables.scss`

**Comment by justkey007** [comment]
For slowness with sass-loader this is true (I have noticed) and to work around I use node-sass directly which is faster. Imports of the global variables file were put in order to compile the scss of each component individually because sass does not allow dynamic file import.

**Comment by payneio** [comment]
Are you able to have hot-reloading by using node-sass directly? I think it's sass-loader that gives me hot reloading, which shows my SCSS changes in the custom template in ~2s, which is great. If I can skirt around sass-loader like you are suggesting, I'd love to try it... will you share how you set that up?

I submitted a PR just now that removes these cyclic imports, which works in my project while using sass-loader. It may really not be the direction you are trying to go, though, so I won't be offended if you don't like the approach.

**Comment by justkey007** [comment]
Yes you can do an automatic recompile using the --watch argument at node-sass. If you use a framework that also observes the generated css files then the hot reload will work. NODE-SASS-WATCH ===> CSS-FILES ===> HOT-RELOAD

**Comment by justkey007** [comment]
"I submitted a PR just now that removes these cyclic imports, which works in my project while using sass-loader. It may really not be the direction you are trying to go, though, so I won't be offended if you don't like the approach." ==> That's understood, I'll take a look at it and validate it
